version: '3'
services:
  web1:
    build: .
    container_name: flask_app1
    ports:
      - "5001:5000"

  web2:
    build: .
    container_name: flask_app2
    ports:
      - "5002:5000"

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
